INSERT INTO ACCOUNT (ACCOUNT_NUMBER,OWNER,BALANCE) VALUES (1,'ALİ CAN', 0.0 );
INSERT INTO ACCOUNT (ACCOUNT_NUMBER, OWNER, BALANCE) VALUES (2, 'VELİ HAN', 1000.0);
INSERT INTO ACCOUNT (ACCOUNT_NUMBER, OWNER, BALANCE) VALUES (3, 'AYŞE YILMAZ', 500.0);


CREATE SEQUENCE account_number_seq START WITH 1 INCREMENT BY 1;
